/*******************************************************************************/
/* Permission is hereby granted, free of charge, to any person or organization */
/* obtaining a copy of the software and accompanying documentation covered by  */
/* this license (the "Software") to use, reproduce, display, distribute,       */
/* execute, and transmit the Software, and to prepare derivative works of the  */
/* Software, and to permit third-parties to whom the Software is furnished to  */
/* do so, all subject to the following:                                        */
/*                                                                             */
/* The copyright notices in the Software and this entire statement, including  */
/* the above license grant, this restriction and the following disclaimer,     */
/* must be included in all copies of the Software, in whole or in part, and    */
/* all derivative works of the Software, unless such copies or derivative      */
/* works are solely in the form of machine-executable object code generated by */
/* a source language processor.                                                */
/*                                                                             */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  */
/* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    */
/* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT   */
/* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE   */
/* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, */
/* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER */
/* DEALINGS IN THE SOFTWARE.                                                   */
/*******************************************************************************/

#include <stdbool.h>
#include <sys/socket.h>
#include <fcntl.h>

#include <libfixposix.h>

int lfp_socket(int domain, int type, int protocol, uint64_t flags)
{
    int _flags = 0;

#if defined(SOCK_CLOEXEC)
    if (flags & O_CLOEXEC) {
        _flags |= SOCK_CLOEXEC;
    }
#endif
#if defined(SOCK_NONBLOCK)
    if (flags & O_NONBLOCK) {
        _flags |= SOCK_NONBLOCK;
    }
#endif

    int fd = socket(domain, type | _flags, protocol);
    if (fd < 0) { goto error_return; };

#if !defined(SOCK_CLOEXEC)
    if ((flags & O_CLOEXEC) && lfp_set_fd_cloexec(fd, true) < 0) {
        goto error_close;
    }
#endif
#if !defined(SOCK_NONBLOCK)
    if ((flags & O_NONBLOCK) && lfp_set_fd_nonblock(fd, true) < 0) {
        goto error_close;
    }
#endif
    return fd;

  error_close:
    close(fd);
  error_return:
    return -1;
}

int lfp_accept(int             sockfd,
               struct sockaddr *addr,
               socklen_t       *addrlen,
               uint64_t        flags)
{
// FIXME: This branch requires that SOCK_CLOEXEC and SOCK_NONBLOCK be
// defined when accept4(2) is present. Should we add an Autoconf check ?
#if defined(HAVE_ACCEPT4)
    int _flags = 0;

    if (flags & O_CLOEXEC) {
        _flags |= SOCK_CLOEXEC;
    }
    if (flags & O_NONBLOCK) {
        _flags |= SOCK_NONBLOCK;
    }

    return accept4(sockfd, addr, addrlen, _flags);
#else
    int fd = accept(sockfd, addr, addrlen);
    if (fd < 0) { goto error_return; }

    if ((flags & O_CLOEXEC) && lfp_set_fd_cloexec(fd, true) < 0) {
        goto error_close;
    }
    if ((flags & O_NONBLOCK) && lfp_set_fd_nonblock(fd, true) < 0) {
        goto error_close;
    }

    return fd;

  error_close:
    close(fd);
  error_return:
    return -1;
#endif // HAVE_ACCEPT4
}



struct cmsghdr* lfp_cmsg_firsthdr (struct msghdr* msgh)
{
  return CMSG_FIRSTHDR(msgh);
}

struct cmsghdr* lfp_cmsg_nxthdr (struct msghdr* msgh, struct cmsghdr* cmsg)
{
  return CMSG_NXTHDR(msgh, cmsg);
}

size_t lfp_cmsg_space (size_t length)
{
  return CMSG_SPACE(length);
}

size_t lfp_cmsg_len (size_t length)
{
  return CMSG_LEN(length);
}

void* lfp_cmsg_data (struct cmsghdr* cmsg)
{
  return CMSG_DATA(cmsg);
}
