/*******************************************************************************/
/* Permission is hereby granted, free of charge, to any person or organization */
/* obtaining a copy of the software and accompanying documentation covered by  */
/* this license (the "Software") to use, reproduce, display, distribute,       */
/* execute, and transmit the Software, and to prepare derivative works of the  */
/* Software, and to permit third-parties to whom the Software is furnished to  */
/* do so, all subject to the following:                                        */
/*                                                                             */
/* The copyright notices in the Software and this entire statement, including  */
/* the above license grant, this restriction and the following disclaimer,     */
/* must be included in all copies of the Software, in whole or in part, and    */
/* all derivative works of the Software, unless such copies or derivative      */
/* works are solely in the form of machine-executable object code generated by */
/* a source language processor.                                                */
/*                                                                             */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  */
/* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    */
/* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT   */
/* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE   */
/* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, */
/* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER */
/* DEALINGS IN THE SOFTWARE.                                                   */
/*******************************************************************************/

#include <lfp/wait.h>

DSO_PUBLIC bool
lfp_wifexited (int status)
{
  return WIFEXITED(status);
}

DSO_PUBLIC int
lfp_wexitstatus (int status)
{
  return WEXITSTATUS(status);
}

DSO_PUBLIC bool
lfp_wifsignaled (int status)
{
  return WIFSIGNALED(status);
}

DSO_PUBLIC int
lfp_wtermsig (int status)
{
  return WTERMSIG(status);
}

DSO_PUBLIC bool
lfp_wcoredump (int status)
{
#ifdef WCOREDUMP
  return WCOREDUMP(status);
#else
  return false;
#endif
}

DSO_PUBLIC bool
lfp_wifstopped (int status)
{
  return WIFSTOPPED(status);
}

DSO_PUBLIC int
lfp_wstopsig (int status)
{
  return WSTOPSIG(status);
}

DSO_PUBLIC bool
lfp_wifcontinued (int status)
{
#ifdef WIFCONTINUED
  return WIFCONTINUED(status);
#else
  return false;
#endif
}
